kind: pipeline
name: build-and-test-amd64

platform:
  os: linux
  arch: arm64

steps:
- name: Build and Test
  image: ubuntu:19.04
  commands:
    - apt-get update -y
    - apt-get install -y make gcc g++ cmake exiv2 libexiv2-dev libboost-all-dev
    - cmake .
    - make
    - ./shiftpicdate -H -8 -D pic --DST -t8
